import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';

/**
 * Styled long-form renderer. Takes article HTML that has already been run
 * through `enrichArticleContent` (headings carry anchor ids) and paints
 * the editorial treatment: serif body, drop-cap, sectioned headings,
 * blockquote pull-quotes, and the `.note` callout hook.
 *
 * The HTML is first-party — authored by trusted WRITER/admin roles and
 * generated by our own build pipeline — so it is bound with
 * `bypassSecurityTrustHtml`. Angular's default `[innerHTML]` sanitizer
 * strips the heading `id`s the table of contents links to, which would
 * silently break every anchor and scroll-spy; bypassing preserves them.
 */
@Component({
  selector: 'mh-article-prose',
  template: `<div class="article-content" [innerHTML]="safeHtml()"></div>`,
  styleUrl: './article-prose.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ArticleProse {
  readonly html = input<string>('');

  private readonly _sanitizer = inject(DomSanitizer);
  readonly safeHtml = computed<SafeHtml>(() => this._sanitizer.bypassSecurityTrustHtml(this.html()));
}
